version: 2
jobs:
    build:
        working_directory: /go/src/github.com/ming-go/lab
        docker:
            - image: circleci/golang
        steps:
            - checkout
            - setup_remote_docker: { reusable: true, docker_layer_caching: true }

            # check go fmt output because it does not report non-zero when there are fmt changes
            - run:
                name: check go fmt
                command: |
                    files=$(go fmt ./...)
                    if [ -n "$files" ]; then
                        echo "The following file(s) do not conform to go fmt:"
                        echo "$files"
                        exit 1
                    fi
            - run: go get -v -t ./...
            - run: go vet ./...
            - run: go test -v -race -cover ./...
            - run:
                name: Lint
                command: |
                    curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0
                    go get -u golang.org/x/lint/golint
                    golint -set_exit_status ./...
                    golangci-lint run \
                        --no-config \
                        -E goconst \
                        -E goimports \
                        -E gocritic \
                        -E golint \
                        -E interfacer \
                        -E maligned \
                        -E misspell \
                        -E stylecheck \
                        -E unconvert \
                        -E unparam \
                        -D errcheck \
                        --skip-dirs vendor ./...
